development:
  adapter: postgresql
  encoding: unicode
  database: ilmd_development
  pool: 5
  username: 
  password: 
  host: ilovemydoctor-localhost.com
  port: 5432

test: &test
  adapter: postgresql
  encoding: unicode
  database: ilmd_test
  pool: 5
  username: 
  password: 
  host: ilovemydoctor-localhost.com
  port: 5432

staging:
  adapter: postgresql
  encoding: unicode
  database: ilmd_production
  pool: 5
  username:
  password:
  host: ilovemydoctor-localhost.com

production:
  adapter: postgresql
  encoding: unicode
  database: ilmd_production
  pool: 5
  username:
  password:
  host: ilovemydoctor-localhost.com
